# Shared public variables for Mongo Docker servers
#
##########################################################
# Warn THIS FILE can't contain any sensitive information #
##########################################################
---
mongo_docker_deploy_base_folder: /nau/ops/mongo
mongo_docker_container_name: mongo
mongo_snmpd_configs: 
  - extend mongo_healthcheck                  /usr/bin/make --jobs 20 --no-print-directory --directory {{ mongo_docker_deploy_base_folder }} silent-healthcheck

mongo_makefile_healthcheck: [ "{{ mongo_docker_deploy_base_folder }}" ]

mongo_docker_admin_username: "{{ MONGO_ADMIN_USER | default('admin') }}"
mongo_docker_admin_password: "{{ MONGO_ADMIN_PASSWORD }}"
mongo_docker_image: docker.io/mongo:7.0
mongo_shell_command: mongosh
